### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by S0vers** [typetechit/restaurant-manager-website#3]
- [ ] [Create a cart page](https://tailwindui.com/components/ecommerce/page-examples/shopping-cart-pages#component-892edc8837628a6df55b8d42a4a5dbbf)
- [ ] [Create a checkout page](https://tailwindui.com/components/ecommerce/page-examples/checkout-pages#component-f5dffb97e3fb18b74edb4ca4864cb359)
- [ ] About page 
- [ ] Contact page
- [ ] privacy policy page
- [ ] terms and condition page
- [ ] Login page
- [ ] forget password
- [ ] register
- [ ] password recovery
- [ ] account page
- [ ] customer profile
- [ ] track order
- [ ] account(OTP) verification
